### ISSUE TITLE
Opening image by URL link

### ISSUE THREAD

**Issue by perervar** [ergec/jQuery-for-PhotoSwipe#2]
Hey.
Thanks for the script. Everything works perfectly.
The only thing that stopped working is the opening of the picture by the link _/#&gid=1&pid=5_.

**Examples:**
working:
http://photoswipe.com/#&gid=1&pid=5
does not work:
https://ergec.github.io/jQuery-for-PhotoSwipe/#&gid=1&pid=2

Tell me please, how can I enable this feature?

**Comment by ergec** [comment]
Hello,
I updated the code, now it should support hash parameters. I suggest using "data-fancybox-gallery" attribute to differentiate multiple galleries on same page.

https://github.com/ergec/jQuery-for-PhotoSwipe/commit/0bba24604535d0c0787e4e901c07e83a78961a7b

**Comment by perervar** [comment]
Thank you!
