### ISSUE TITLE
Gallery Object

### ISSUE THREAD

**Issue by davidfwall** [ergec/jQuery-for-PhotoSwipe#3]
Not an issue more a plea for help — just wondering if you have an example of the syntax for accessing methods and properties from the API. As noted in the demo code—

`//with `gallery` object you can access all methods and properties described here http://photoswipe.com/documentation/api.html
`

I’m hoping to open a single image in the zoomed in view, which appears to be possible using zoomTo: https://github.com/dimsemenov/PhotoSwipe/issues/795

Thanks in advance

**Comment by ergec** [comment]
Try like this.
```
galleryOpen: function (gallery) {
    gallery.toggleDesktopZoom();
}
```

**Comment by davidfwall** [comment]
Amazing thank you
