### ISSUE TITLE
(.pswp) element

### ISSUE THREAD

**Issue by weilinzung** [ergec/jQuery-for-PhotoSwipe#4]
PLEASE add a condition script to detect if the gallery(ID OR CLASS name) exist then add the ` (.pswp) element`, right now these elements are added to the entire site, I think it should add these when the page has gallery.

Also please add this project to `bower`.

hope if you can fix this,
thanks!

**Comment by ergec** [comment]
Could you please provide a working demo replicating the issue.

**Comment by weilinzung** [comment]
I don't have the demo to share, but if you looking into your site: https://ergec.github.io/jQuery-for-PhotoSwipe/

all of these elements would just added to before `</body>` tag, I think would be better just add these to only the pages use the gallery. I my case, all of these elements are added to all pages, even page doesn't have gallery.

`<div class="pswp" tabindex="-1" role="dialog" aria-hidden="true"><div class="pswp__bg"></div><div class="pswp__scroll-wrap"><div class="pswp__container"><div class="pswp__item"></div><div class="pswp__item"></div><div class="pswp__item"></div></div><div class="pswp__ui pswp__ui--hidden"><div class="pswp__top-bar"><div class="pswp__counter"></div><button class="pswp__button pswp__button--close" title="Close (Esc)"></button><button class="pswp__button pswp__button--share" title="Share"></button><button class="pswp__button pswp__button--fs" title="Toggle fullscreen"></button><button class="pswp__button pswp__button--zoom" title="Zoom in/out"></button><div class="pswp__preloader"><div class="pswp__preloader__icn"><div class="pswp__preloader__cut"><div class="pswp__preloader__donut"></div></div></div></div></div><div class="pswp__share-modal pswp__share-modal--hidden pswp__single-tap"><div class="pswp__share-tooltip"></div> </div><button class="pswp__button pswp__button--arrow--left" title="Previous (arrow left)"></button><button class="pswp__button pswp__button--arrow--right" title="Next (arrow right)"></button><div class="pswp__caption"><div class="pswp__caption__center"></div></div></div></div></div>`

**Comment by ergec** [comment]
fixed

https://github.com/ergec/jQuery-for-PhotoSwipe/commit/a96ba42fa8e04172402b8abea12fee348a1b6654#diff-65bd2ce2456951101d45e98ab367c427
