### ISSUE TITLE
update PhotoSwipe Scrpit

### ISSUE THREAD

**Issue by weilinzung** [ergec/jQuery-for-PhotoSwipe#6]
Can you do the latest PhotoSwipe script update for this repo? I think it fixed couple issues. 
Also register to bower would be great: https://bower.io/docs/creating-packages/

Thanks!

**Comment by ergec** [comment]
Updated PhotoSwipe script to latest version. Never did bower before and no idea what it is (shame on me :P) but i'll check it out :)

https://github.com/ergec/jQuery-for-PhotoSwipe/commit/69b2a115dab0875816d699ace263e022b14e6dfd

**Comment by weilinzung** [comment]
I think should be easy to follow: https://bower.io/docs/creating-packages/#register

**Comment by weilinzung** [comment]
any news by adding it to bower?
