### ISSUE TITLE
Zoom animation effect

### ISSUE THREAD

**Issue by svriend** [ergec/jQuery-for-PhotoSwipe#7]
Hi @ergec ,

Thanks for your work on jqPhotoSwipe. I'm not a coder and have a very limited experience in building websites but I seem to have been able to get your jqPhotoSwipe gallery working. So good work on your part.
I noticed however that there is no zoom animation when opening a gallery (this also seems to be the case in your demo page). Is it simply an option that is disabled? If so, do you know how I can enable it?

If you can help me with it I would appreciate it very much, if you don't have the time I understand completely.
Thanks again for your work,
kind regards,
Stefan

**Comment by rinogo** [comment]
Good observation! I'm glad I saw this as I was considering using this plugin, but might not if key features like this are missing. My guess is that one of two things is causing this:

1. The plugin might include an outdated version of Photoswipe.
2. The plugin might have disabled this functionality to allow images to be specified without dimensions.

Ultimately, I'm not sure - I'd have to dive in to the code to find out. But I'll likely just follow [this guide](https://webdesign.tutsplus.com/tutorials/the-perfect-lightbox-using-photoswipe-with-jquery--cms-23587), [this pen](https://codepen.io/alienlebarge/pen/Kdrxga), or something similar to create my own jQuery wrapper.
