### ISSUE TITLE
Bug when manually clicking preloaded gallery images

### ISSUE THREAD

**Issue by trnelson** [ergec/jQuery-for-PhotoSwipe#8]
Thank you for this awesome script--exactly what I needed to move from fancybox to PhotoSwipe!

I found a bug that happens under certain conditions when using `fancybox-group` gallery mode. Take for example the "Single Combined Image Gallery (Forced)" on your demo page (https://ergec.github.io/jQuery-for-PhotoSwipe/).

No issue:

1. Click image 1 (works)
2. (close preview)
3. Click image 3 (works)

Reproducible issue:

1. Click image 1 (works)
2. (close preview)
3. Click image 2 (works)
4. (close preview)
4. Click image 3 (does not work - image size remains 0px, 0px)

It seems like the issue is caused by PhotoSwipe's gallery preloading for the images [N, N-1, N+1], and may be a bug in PhotoSwipe. When clicking through the gallery images manually (closing preview each time) PhotoSwipe does not appear to emit an `imageLoadComplete` event _for other items that should be included for preload_ and so your handler to update the image size is never triggered:

```
_photoswipe.galleries[$galleryid2].obj.listen("imageLoadComplete", function (index, item) {
    ...
}
```

I started looking into a fix but short on time and just disabled gallery mode for now. If you happen to have any ideas for a fix, please let me know. Thank you again!

**Comment by ergec** [comment]
Hello thanks for the report. I think it's ok now.

https://github.com/ergec/jQuery-for-PhotoSwipe/commit/883c209d29b45c6864c8ab61ba2560ecb7385e90#diff-65bd2ce2456951101d45e98ab367c427

**Comment by trnelson** [comment]
Thank you for the quick fix! Someone else on my team tested the fix and it seems to be working properly now. I appreciate your help!
